-- PARTE 1/6: Entradas (renda) — bloco 6
do $$ declare uid uuid := '69f852bc-af5a-4f11-b293-37bf2f809018'; begin
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Concerto Carro - 06/10',419.70,'2024-09-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',13748.50,'2024-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tauan - Jogo SCCP',136.00,'2024-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Leandro - Presente Tata',87.00,'2024-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2024-09-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Dolares',1000.00,'2024-09-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'FGTS - Antecipação',8358.22,'2024-09-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',0.12,'2024-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',600.00,'2024-10-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',480.00,'2024-10-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Carro 08/18',1306.22,'2024-10-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Empréstimo - 03/03',2552.63,'2024-10-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Overboard - 09/10',182.20,'2024-10-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Concerto Carro - 07/10',419.70,'2024-10-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',13748.50,'2024-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2024-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Leandro - Presente Tata - 02/03',87.00,'2024-10-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',0.48,'2024-10-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Sueli - Convênio',500.00,'2024-11-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gera - Azeites',550.00,'2024-11-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Uber - Nov - Semana 01',486.59,'2024-11-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Uber - Nov - Semana 02',633.84,'2024-11-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Carro 09/18',1306.22,'2024-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Overboard - 10/10',182.20,'2024-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Concerto Carro - 08/10',419.70,'2024-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Uber - Nov - Semana 03',717.87,'2024-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',13748.50,'2024-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2024-11-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Dolares',1000.00,'2024-11-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Leandro - Presente Tata - 03/03',87.00,'2024-11-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',0.96,'2024-10-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Uber - Nov - Semana 04',241.03,'2024-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Sergio - Obra Casa',998.35,'2024-12-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Uber - Dez - Semana 01',522.30,'2024-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 02/02',4408.71,'2024-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',13748.50,'2024-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Serodio Turismo - Hospedagem',591.39,'2024-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Metropole Tintas - Reembolso',121.65,'2024-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',505.00,'2024-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Dolares',1000.00,'2024-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Carro 10/18',1306.22,'2024-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Sergio - Textura',800.00,'2024-12-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Uber - Dez - Semana 02',345.79,'2024-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Concerto Carro - 09/10',419.70,'2024-12-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Natiruts - 01/10',60.00,'2024-12-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Uber - Dez - Semana 03',528.21,'2024-12-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',1.06,'2024-10-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2013-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'O Rappa Renan',100.00,'2013-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Mãe',220.00,'2013-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3702.63,'2013-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo',3500.00,'2013-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Retorno Privalia',111.95,'2013-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Conta Juridica',2.00,'2013-02-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3500.00,'2013-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ana Paula',27.14,'2013-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Débitos',28.26,'2013-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Taxas',3.55,'2013-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3500.00,'2013-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Marcelinho 01/02',60.00,'2013-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Mãe Cajobi',200.00,'2013-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Giu Cartão de Visita',90.00,'2013-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rio de Janeiro',300.00,'2013-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Marcelinho 02/02',60.00,'2013-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3500.00,'2013-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Despesas Viagem Rj',1082.25,'2013-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Active Silvana 01/03',100.00,'2013-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3500.00,'2013-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Viagem Embraer',226.63,'2013-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Devolução Taisa',293.00,'2013-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Devolução Mãe',200.00,'2013-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Active Silvana 02/03',100.00,'2013-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ana Paula',14.00,'2013-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3500.00,'2013-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Visitas',67.56,'2013-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Active Silvana 03/03',115.00,'2013-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ana Paula',23.56,'2013-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Sob Medida',5689.58,'2013-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3500.00,'2013-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RVL Shake Mix Giu / 42 uni.',200.00,'2013-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',4058.38,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pai 01/03',30.00,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pai 02/03',30.00,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pai 03/03',10.00,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Notebook Pai 01/10',130.00,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ana Paula',39.26,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nuit Giu / 24 latas',73.00,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nuit Giu / 12 latas',35.00,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RVL Snack Bar Giu / 7 uni.',26.25,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RVL Shake Mix Giu / 7 uni.',30.38,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Emv Giu / 6 latas 01/02',35.37,'2013-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',4000.00,'2013-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',76.50,'2013-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Passagem Pai 01/02',200.00,'2013-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Active Silvana / 1 Tetrapark',60.00,'2013-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',4000.03,'2013-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',152.00,'2013-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',76.50,'2013-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Active Giu / 1 Caixa',194.16,'2013-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Emv Giu / 6 latas 02/02',11.18,'2013-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'MX Silvana / 1 Garrafa',100.00,'2013-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',4000.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',152.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',76.50,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Passagem Pai 02/02',200.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pai 03/03',20.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Notebook Pai 02/10',130.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Notebook Pai 03/10',130.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Notebook Pai 04/10',20.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Mãe',250.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Retirada Nota Fiscal Paulista',25.00,'2013-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Mãe',1200.00,'2013-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Notebook Pai 04/10',110.00,'2013-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Notebook Pai 05/10',30.00,'2013-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Spotify - Eric Teixeira',26.90,'2019-01-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Mãe - C. Crédito',500.00,'2019-01-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Fê - 01/05',44.95,'2019-01-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Site Serodio - 03/03',300.00,'2019-01-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',260.00,'2019-01-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Lê - 01/05',44.95,'2019-01-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',5853.61,'2019-01-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Horas Extra',913.76,'2019-01-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Lourders - Netflix',114.00,'2019-02-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',620.00,'2019-02-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo',200.30,'2019-02-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Conta Vivo - Nicole',100.00,'2019-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Fabinho - 01/05',44.95,'2019-02-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Férias',3045.54,'2019-02-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Férias',1189.66,'2019-02-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Abono pecuniário',2232.48,'2019-02-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Abono pecuniário',849.76,'2019-02-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',100.00,'2019-02-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ana Paula - Geladeira 07/10',100.00,'2019-02-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 01/02',4396.77,'2019-02-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Fastshop - Celular Edmar - 09/12',58.50,'2019-02-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Fastshop - Celular Edmar - 10/12',58.50,'2019-02-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Lê - 02/05',44.95,'2019-02-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',3519.77,'2019-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Felícia - 02/05',44.95,'2019-02-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',600.00,'2019-03-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole',100.00,'2019-03-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Lê - 03/05',44.95,'2019-03-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Felícia - 03/05',44.95,'2019-03-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - PLR',608.57,'2019-03-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',356.00,'2019-03-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',5473.62,'2019-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hospedagem - Academia',215.00,'2019-03-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RegistroBR - Academia',40.00,'2019-03-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Fabinho - 02/05',44.95,'2019-03-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Fabinho - 03/05',44.95,'2019-03-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',500.00,'2019-03-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Léo - Churrasco - 27/02',49.00,'2019-04-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Léo - Okazaki - 03/03',120.50,'2019-04-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Léo - Açai Formosa - 30/03',12.50,'2019-04-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Felícia - 04/05',44.95,'2019-04-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Fastshop - Celular Edmar - 11/12',60.00,'2019-04-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Fastshop - Celular Edmar - 12/12',60.00,'2019-04-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ana - Spotify',26.90,'2019-04-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',356.00,'2019-04-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Lê - 04/05',44.95,'2019-04-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',5946.92,'2019-04-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Fabinho - 04/05',44.95,'2019-04-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Fabinho - 05/05',44.95,'2019-04-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',500.00,'2019-04-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Emerson - Churrasco',64.00,'2019-05-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Felícia - 05/05',44.95,'2019-05-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata - Lê - 05/05',44.95,'2019-05-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6715.63,'2019-05-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Horas Extra',8000.00,'2019-05-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Psicologa - Nicole',264.50,'2019-05-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Psicologa - Nicole',264.50,'2019-05-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',500.00,'2019-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Multa Nicole',136.00,'2019-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Léo - Netflix',45.90,'2019-06-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6110.05,'2019-06-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 01/02',112.50,'2019-06-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  01/10',100.00,'2019-06-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  01/10',110.00,'2019-06-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',600.00,'2019-07-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Andressa - Spotify',26.90,'2019-07-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Eric Teixeira - Spotify',26.90,'2019-07-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  02/10',210.00,'2019-07-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6110.05,'2019-07-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Samara - Ração Gatona',50.00,'2019-07-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',490.00,'2019-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Luiza - Ingresso Hillsong',92.00,'2019-08-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'IR - Restituição',2746.50,'2019-08-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  03/10',210.00,'2019-08-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6110.05,'2019-08-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ni - Contas Casa',500.00,'2019-08-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ni - Faculdade',270.00,'2019-08-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ni - Sandy & Junior',50.00,'2019-08-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ana Paula - Spotify',26.80,'2019-09-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Léo - Reembolso Uber',55.28,'2019-09-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Léo - Netflix',45.90,'2019-09-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Sô',350.00,'2019-09-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6110.05,'2019-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Horas Extra',4603.30,'2019-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Dissídio',300.00,'2019-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  04/10',200.00,'2019-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',500.00,'2019-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Mãe',1252.99,'2019-10-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',100.00,'2019-10-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  05/10',220.00,'2019-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6110.05,'2019-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',1000.00,'2019-10-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech - 01/20',350.00,'2019-11-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Viagem Cajobi',240.00,'2019-11-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emerson - Viagem Cajobi',240.00,'2019-11-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole Saúde',130.00,'2019-11-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - FGTS Saque Imediato',500.00,'2019-11-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6133.43,'2019-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Serodio - Hospedagem',349.00,'2019-11-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole - 11/2019',550.00,'2019-11-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Buffet Casamento',750.00,'2019-11-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Andressa - Spotify',26.90,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pontos - Galera Cajobi',1960.00,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Taxas - Galera Cajobi',387.84,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  06/10',200.00,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pontos - Sônia',336.00,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Taxas - Sônia',64.00,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pontos - Eva',336.00,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Taxas - Eva',64.00,'2019-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Netflix',45.90,'2019-12-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pontos - Familia Solange',1316.00,'2019-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Taxas - Familia Solange',258.86,'2019-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Amigos RDI',1500.00,'2019-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Contas Nicole',500.00,'2019-12-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Tia Neide',300.00,'2019-12-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Dona Ruty',470.00,'2019-12-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Du',100.00,'2019-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Lia e Tia Neuza',200.00,'2019-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Piano',600.00,'2019-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6133.43,'2019-12-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 02/02',3347.28,'2019-12-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'SmartTV - Mãe  07/10',209.00,'2019-12-23','{}','REALIZED');
end $$;
