-- PARTE 1/6: Entradas (renda) — bloco 3
do $$ declare uid uuid := '69f852bc-af5a-4f11-b293-37bf2f809018'; begin
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole Almoço e Cabelo',50.00,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Loja Rocha - Ni - 02/03 - 26/08',86.00,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Loja Rocha - Ni - 03/03 - 26/08',86.00,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Curso Alura -Nicole - 02/12',42.50,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Englishtown Nicole',67.50,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Ativação Novembro - Nicole',322.00,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Farmácia Nicole - 01/03',79.96,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Almoço Convenção Hinode - 25/11',41.80,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Almoço Convenção Hinode - 26/11',36.30,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Outback - 27/11',50.00,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Curso Nicole - 29/11',350.00,'2017-12-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Curso Alura - Nicole - 03/12',45.00,'2017-12-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Manuel',120.00,'2017-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode Gisele (Amiga Moranga)',120.00,'2017-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode Gold 09 - Mãe Moranga - 01/02',60.00,'2017-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode Renato (Moranga)  - 03/03',196.00,'2017-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Despesas Gabs',61.00,'2017-12-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Rosi Sarti',82.50,'2017-12-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Zé Sarti',120.00,'2017-12-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo TSI',6000.00,'2017-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Bônus Mensal',810.30,'2017-12-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Ana 12/2017',87.90,'2017-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Churrasco 15/11 - Ana',21.94,'2017-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode Batom Matify Marrom - Ana Paula',15.00,'2017-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Ed 12/2017',87.90,'2017-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Churrasco 15/11 - Ed',21.94,'2017-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Mãe 12/2017',87.90,'2017-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Joli Óleo em Creme',50.00,'2017-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Mae - Lentes - 02/03',100.00,'2017-12-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Farmácia Léo - 02/03',55.16,'2017-12-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Beatriz Leao',150.00,'2017-12-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Renan - Contador',300.00,'2017-12-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Renan Lacerda',96.80,'2017-12-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Retorno Nfe Paulista',60.00,'2017-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Retorno Nfe Paulista',33.00,'2017-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode - Fabiana Demarchi',100.00,'2017-12-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode Latitude Expedition - Ademir - 02/02',60.00,'2017-12-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hinode Gold 62 - Roberto - 01/02',60.00,'2017-12-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',2500.00,'2012-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Ana Paula',100.00,'2012-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Tata',70.00,'2012-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',2500.00,'2012-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-03-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'PLR Activas',83.33,'2012-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Mãe',110.00,'2012-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Apostilas',133.30,'2012-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário 06/11',2000.00,'2012-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário 10/11',2500.00,'2012-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ingresso Tata / Ton',200.00,'2012-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Mãe',110.00,'2012-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata Voo Perdido',101.56,'2012-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata Voo Novo',88.00,'2012-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata Voo Novo Entr.',21.57,'2012-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Volta Tata',15.99,'2012-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Restate Poupança',700.00,'2012-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Volta Ton',85.00,'2012-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Ana Paula',104.00,'2012-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Poupança',800.00,'2012-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Volta Tata',70.00,'2012-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata Voo Novo',80.00,'2012-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Conta Água',60.00,'2012-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3076.29,'2012-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Lente Mãe 01/03',80.00,'2012-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Conta luz',115.42,'2012-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Emprestimo Mãe',110.00,'2012-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'ACHEI !!!',100.00,'2012-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Fio',2500.00,'2012-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Mãe',3707.28,'2012-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Poupança',200.00,'2012-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Pai',300.00,'2012-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Tata',500.00,'2012-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Pai',100.00,'2012-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Mãe',80.00,'2012-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Tata',105.00,'2012-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Pai',800.00,'2012-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Mãe',110.00,'2012-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Tata',453.00,'2012-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Banco Seguro Vida Devolução',9.79,'2012-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',3000.00,'2012-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',5.00,'2012-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5000.00,'2015-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',99.00,'2015-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Ana Paula 12/12',148.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Aniversário Ed',390.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Creme Hinode  Marcelo',137.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Renan O Rappa',70.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Transf Eric Teixeira',17.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Transf Dalton',17.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Silvana',20.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Rogério',20.00,'2015-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',108.00,'2015-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rogério PFC',40.00,'2015-02-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ana Paula  Depósito',50.00,'2015-02-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Conta Mãe',42.00,'2015-02-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagamento Hinode',74.50,'2015-02-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-03-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-03-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',108.00,'2015-03-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Perfume Mãe',100.00,'2015-03-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Vendas Hinode',59.70,'2015-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Fiel Torcedor Tata',80.00,'2015-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Vendas Hinode Lu 01/02',55.20,'2015-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',108.00,'2015-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ingresso Cor x San Lorenzo',110.00,'2015-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Poupança',400.00,'2015-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Oi',250.00,'2015-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'TFE 2012 Dalton',102.67,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',108.00,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Ana Paula',154.98,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Ana Paula 2',126.61,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ana Paula  Açougue',78.75,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ana Paula  Bolo',18.48,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Léo 04/05',133.00,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Léo 05/05',117.00,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Gasolina Marcus',150.00,'2015-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Poupança',400.00,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Poupança',300.00,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Ni CH & X',220.00,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Léo Entrada PlayStation 4',330.00,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Deposito',90.00,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Tata Ingressos',136.40,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Tata NX Zero',100.00,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Ana Paula',400.00,'2015-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'TFE 2014 Dalton',83.72,'2015-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',108.00,'2015-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Higienização Carro  Dalton',100.00,'2015-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Léo PlayStation 4 - 01/04',432.00,'2015-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Léo',133.00,'2015-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Poupança',800.00,'2015-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ana Paula',5.20,'2015-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'TFE 2015 Dalton',64.80,'2015-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',108.00,'2015-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Resgate Poupança',380.00,'2015-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Léo PlayStation 4 - 02/04',430.00,'2015-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Léo',130.00,'2015-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Contador Dalton',165.00,'2015-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Imposto Dalton',61.20,'2015-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Dalton',1105.30,'2015-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Deposito Ni',100.00,'2015-07-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ingresso Corinthians x Sport',30.00,'2015-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Farmácia Ni 16/07',125.00,'2015-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Sapato Ni',55.00,'2015-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Léo PlayStation 4 03/04',400.00,'2015-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Léo',100.00,'2015-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Bancário',6000.00,'2015-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Mãe Tonaki',250.00,'2015-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Recebimentos',83.56,'2015-09-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Tata  Fiel Torcedor',60.00,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Depósito Ana P.  Pag C. Crédito Mãe',180.23,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Depósito Mãe  Pag C. Crédito Mãe',80.00,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Cauê  Camisa Corinthians',100.00,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Tata  Fiel Torcedor',90.00,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Tata  Fiel Torcedor',220.00,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Léo PlayStation 4 - 04/04',431.00,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Contas Léo',133.00,'2015-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ingressos SCCP x Goias',120.00,'2015-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Buzios Ni',680.00,'2015-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Zensei Ni/Fernandinho 22/08',63.28,'2015-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Supermercado Ni 22/08',51.71,'2015-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Passagem Recife Ida Ni',410.93,'2015-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Outback Ni 21/08',74.05,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Farmácia Ni 21/08',68.18,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Perfumes Ni',100.00,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Roupas Ni 01/03',142.50,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Churrasco 12/10',61.86,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Empréstimo Ni 16/10',374.00,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Ingressos Flamengo e Coritiba',200.00,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Tata Jaqueta Corinthians 01/02',70.00,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Ingressos Ana Paula',313.50,'2015-10-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Bancário  Viagem Nordeste',7500.00,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Mercado Pago Devolução',69.96,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Viagem Boituva Gabs e Léo',60.00,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Mãe Churrasco',100.00,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pizza Mãe 06/11',50.00,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Recarga Celular Ni',35.00,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Roupas Ni 02/03',145.00,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Praxi',63.72,'2015-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Estorno Juros Financiamento',104.70,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Tata Jaqueta Corinthians 02/02',70.00,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Contas Léo',130.00,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Roupas Ni 03/03',142.50,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Farmácia Ni 07/11',38.00,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Farmácia Ni 21/10',105.00,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Almoço Casa Ni 31/10',55.00,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ni Churrasco',59.50,'2015-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Salário',5500.00,'2015-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Bancário - Viagem Nordeste',2100.00,'2015-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ingresso Thamy',115.00,'2015-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag Ni Churrasco',10.50,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Fiel Torcedor - SCCP x sp - Ni',70.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Curso Ni - 01/02',34.76,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Curso Ni - 02/02',34.76,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Farmácia Ni 13/11 - 01/02',36.75,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Farmácia Ni 13/11 - 02/02',36.75,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Passagem Recife Volta Ni - 01/03',156.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Passagem Recife Volta Ni - 02/03',156.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Passagem Recife Volta Ni - 03/03',156.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pousada Natal Ni',100.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pousada João Pessoa Ni',49.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pag. Pousada Porto de Galinhas Ni',52.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Farmácia Ni - 21/11',42.69,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Perfumaria Ni - 01/02',61.50,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Perfumaria Ni - 02/02',61.50,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Almoço Craisa Ni',40.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Jantar Si Señor Ni',50.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Recarga Nii 24/11',35.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Despesa Dieta Ni 30/11',153.36,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Sapato Ni',56.69,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Perfumaria Ni - 02',6.74,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Controle Ana Paula 01/02',92.50,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Jantar Si Señor Ana Paula',129.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Show H & J - Ana Paula',115.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pneus Ana Paula',500.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pneus Carrefour 01/03 - Mãe',250.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Mãe Roupas Gotinha 12/12',130.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Food Truck Mãe 13/12',70.00,'2015-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Eric Teixeira - Spotify',34.90,'2022-01-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2151.15,'2022-01-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2022-01-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',20.00,'2022-01-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Lourdes - Netflix',336.00,'2022-01-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',9053.10,'2022-01-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-01-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Renan - Estacionamento',50.00,'2022-01-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Carrefour - Pneus - 05/06',100.00,'2022-01-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Carrefour - Pneus - 05/06',85.00,'2022-01-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',27.38,'2022-01-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',910.06,'2022-01-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',520.00,'2022-01-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -17/20',150.00,'2022-01-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -18/20',150.00,'2022-01-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1090.00,'2022-01-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-01-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Caixa FGTS Aniversário - Nicole',1110.00,'2022-01-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Caixa FGTS Aniversário - Thiago',5000.00,'2022-01-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Caixa FGTS Aniversário - Thiago',1040.00,'2022-01-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',4800.00,'2022-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1226.71,'2022-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',128.80,'2022-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',41.96,'2022-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',260.00,'2022-02-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3000.00,'2022-02-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',450.00,'2022-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',312.00,'2022-02-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Churrasco',120.00,'2022-02-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Venda Onix LT 2014 - 1.4 Aut',44610.00,'2022-02-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',10110.00,'2022-02-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2022-02-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',4300.00,'2022-02-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',10923.14,'2022-02-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso - Azul Seguros',150.08,'2022-02-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',260.00,'2022-02-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',9255.73,'2022-02-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Carrefour - Pneus - 05/06',110.00,'2022-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',850.00,'2022-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2000.00,'2022-02-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',17.39,'2022-02-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',381.00,'2022-03-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',8.30,'2022-03-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1685.00,'2022-03-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2022-03-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',326.00,'2022-03-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-03-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Spotify',34.90,'2022-03-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2000.00,'2022-03-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Robô Aspirador',500.00,'2022-03-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - PLR',829.87,'2022-03-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',162.00,'2022-03-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',4800.00,'2022-03-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Robô Aspirador',283.12,'2022-03-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',870.00,'2022-03-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1500.00,'2022-03-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -19/20',150.00,'2022-03-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -20/20',150.00,'2022-03-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2022-03-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10784.03,'2022-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Carrefour - Pneus - 06/06',110.00,'2022-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2022-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',280.00,'2022-03-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',234.00,'2022-03-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',269.00,'2022-03-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',131.71,'2022-03-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',119.74,'2022-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-04-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',290.00,'2022-04-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-04-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1100.00,'2022-04-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',409.41,'2022-04-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',657.00,'2022-04-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',103.60,'2022-04-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',580.00,'2022-04-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Robô Aspirador',600.00,'2022-04-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3000.00,'2022-04-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1500.00,'2022-04-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',74.00,'2022-04-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2022-04-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2022-04-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',290.00,'2022-04-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-04-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2500.00,'2022-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1618.00,'2022-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Férias',6336.12,'2022-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Férias',3193.33,'2022-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Abono pecuniário',4790.00,'2022-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Abono pecuniário',1596.67,'2022-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 01/02',7185.00,'2022-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Jantar',67.70,'2022-04-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',290.00,'2022-04-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',319.00,'2022-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3295.00,'2022-04-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3500.00,'2022-04-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',62.50,'2022-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8880.55,'2022-04-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',35.00,'2022-04-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Leo - Fifa 22',50.00,'2022-04-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',610.00,'2022-04-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',50.89,'2022-05-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',900.00,'2022-05-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2022-05-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole FGTS',1000.00,'2022-05-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Saúde - Nicole',212.34,'2022-05-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1760.00,'2022-05-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1378.00,'2022-05-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2022-05-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',657.00,'2022-05-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Du - Cinemark',77.60,'2022-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Presente Mãe',150.00,'2022-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',550.00,'2022-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',260.00,'2022-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2022-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',400.00,'2022-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2000.00,'2022-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Faculdade',200.00,'2022-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Lucas - Ingresso Corinthians',52.00,'2022-05-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-05-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-05-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1500.00,'2022-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1520.00,'2022-05-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Saúde - Nicole',283.12,'2022-05-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2022-05-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6342.59,'2022-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Thiago FGTS',1000.00,'2022-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',33.40,'2022-05-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2022-05-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Presente Mãe',150.00,'2022-05-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',110.00,'2022-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',50.00,'2022-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',70.19,'2022-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2022-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',362.03,'2022-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',90.00,'2022-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',66.00,'2022-06-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-06-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10784.03,'2022-06-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2022-06-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2022-06-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2022-06-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',43.31,'2022-06-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Estorno Nubank',15.69,'2022-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',450.00,'2022-06-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -21/40',150.00,'2022-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -22/40',150.00,'2022-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -23/40',150.00,'2022-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',705.71,'2022-06-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',562.03,'2022-06-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2022-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Presente Helena',100.00,'2022-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'IR - Restituição',1306.50,'2022-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',20.31,'2022-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-07-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Saúde',353.89,'2022-07-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'FGTS - Saque Aniversário',303.25,'2022-07-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Eric Teixeira - Spotify',34.90,'2022-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2022-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Odontologia',124.93,'2022-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Tata',350.00,'2022-07-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',169.27,'2022-07-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2022-07-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2022-07-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',450.00,'2022-07-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-07-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',180.00,'2022-07-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Livro Amazon',27.93,'2022-07-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10784.03,'2022-07-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2022-07-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-07-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2022-07-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2022-07-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1300.00,'2022-07-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',22.18,'2022-07-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2022-08-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Compra Teste',44.00,'2022-08-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Bradesco Saúde - Reembolso',4968.61,'2022-08-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Aux. Carro',800.00,'2022-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Aux. Carro',1122.66,'2022-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2022-08-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',848.00,'2022-08-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',400.00,'2022-08-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 01/12',268.80,'2022-08-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Parcela Faculdade',299.00,'2022-08-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',351.45,'2022-08-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3240.00,'2022-08-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',309.69,'2022-08-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Reembolso Visto / Honorários',1248.00,'2022-08-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',761.01,'2022-08-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-08-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',180.00,'2022-08-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10784.03,'2022-08-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2022-08-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2022-08-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2022-08-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',40.00,'2022-08-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',10.23,'2022-08-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Renan - 20 figurinhas',16.00,'2022-09-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Matheus - 35 figurinhas',28.00,'2022-09-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-09-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',210.00,'2022-09-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',34.00,'2022-09-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 02/12',269.00,'2022-09-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Aux. Carro',1122.02,'2022-09-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',180.00,'2022-09-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1050.00,'2022-09-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',60.00,'2022-09-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',8.60,'2022-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ring Fit - Venda ML',450.00,'2022-09-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -24/40',150.00,'2022-09-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -25/40',150.00,'2022-09-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -26/40',150.00,'2022-09-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Celso - Ingressos Corinthians',300.00,'2022-09-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1006.60,'2022-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10756.53,'2022-09-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2022-09-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata e Bea - Ingressos Corinthians',300.00,'2022-09-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Henrique - Ingressos Corinthians',150.00,'2022-09-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Du - Jantar Burguer',46.00,'2022-09-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',138.00,'2022-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',8.31,'2022-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',360.00,'2022-10-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2022-10-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2022-10-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 03/12',269.00,'2022-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Aux. Carro',1122.16,'2022-10-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Dentista',150.00,'2022-10-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2022-10-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',180.00,'2022-10-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Jantar Pizza',34.89,'2022-10-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2022-10-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',120.00,'2022-10-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Conta Luz',283.62,'2022-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10756.53,'2022-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',4.87,'2022-10-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 04/12',269.00,'2022-11-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Aux. Carro',1121.16,'2022-11-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',250.00,'2022-11-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pedro - Venda 02 Xiaomi ReadMe 9s',1200.00,'2022-11-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',30.00,'2022-11-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',103.95,'2022-11-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',30.00,'2022-11-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',30.00,'2022-11-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',175.20,'2022-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10756.53,'2022-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Serodio Turismo - Renovação Hospedagem',475.20,'2022-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2022-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Churrasco',120.00,'2022-11-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -27/40',150.00,'2022-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -28/40',150.00,'2022-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula',50.00,'2022-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso - Compras Chacara',428.00,'2022-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',4.01,'2022-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Terapia',241.00,'2022-12-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Euro Trip',1100.00,'2022-12-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Euro Trip',1000.00,'2022-12-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3396.00,'2022-12-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',480.00,'2022-12-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Farmácia',27.00,'2022-12-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 05/12',269.00,'2022-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Bradesco - Reembolso Terapia',283.12,'2022-12-05','{}','REALIZED');
end $$;
