-- PARTE 1/6: Entradas (renda) — bloco 1
do $$ declare uid uuid := '69f852bc-af5a-4f11-b293-37bf2f809018'; begin
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Compras ML',192.00,'2023-01-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata e Bea - Casa Maragogi',2760.00,'2023-01-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco',283.12,'2023-01-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',341.22,'2023-01-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',176.90,'2023-01-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2023-01-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 06/12',269.00,'2023-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',408.00,'2023-01-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2023-01-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -29/40',150.00,'2023-01-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - Hospedagem',197.93,'2023-01-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco',353.89,'2023-01-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2023-01-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Aux. Carro',1222.00,'2023-01-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',45.70,'2023-01-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - IPTU Casa Maragogi',1300.00,'2023-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',19.65,'2023-01-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Comidas Chacará',970.00,'2023-01-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-01-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11890.73,'2023-01-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Spotify - Eric Teixeira',34.90,'2023-01-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',20.00,'2023-01-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',20.00,'2023-01-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2023-01-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Passeio de Buggy',100.00,'2023-01-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',627.00,'2023-01-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',607.00,'2023-01-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',0.80,'2023-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Parcela 69/100 - Casa Maragogi',925.00,'2023-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.05,'2022-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 07/12',269.00,'2023-02-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Aux. Carro',1200.00,'2023-02-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Yakisoba',100.00,'2023-02-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-02-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -30/40',150.00,'2023-02-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -31/40',150.00,'2023-02-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2023-02-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-02-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-02-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2023-02-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11890.73,'2023-02-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Despesas Gera',1200.00,'2023-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',30.00,'2023-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.07,'2023-02-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Parcela 70/100 - Casa Maragogi',924.90,'2023-03-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 08/12',269.00,'2023-03-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-03-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2023-03-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2023-03-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',5000.00,'2023-03-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1740.00,'2023-03-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',859.00,'2023-03-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',50.00,'2023-03-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata - Pagto Calça Renner',160.00,'2023-03-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',3000.00,'2023-03-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',4237.00,'2023-03-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',60.00,'2023-03-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',2000.00,'2023-03-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11890.73,'2023-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - PLR',676.84,'2023-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',396.00,'2023-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Parcela 71/100 - Casa Maragogi',924.90,'2023-03-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa (Sobra)',75.10,'2023-03-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-03-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.08,'2023-03-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 09/12',269.00,'2023-04-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2023-04-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',1900.00,'2023-04-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Viagem Nordeste - Sobra',6.90,'2023-04-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',4100.00,'2023-04-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2023-04-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - McDonalds',21.00,'2023-04-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11890.73,'2023-04-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-04-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-04-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -32/40',150.00,'2023-04-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -33/40',150.00,'2023-04-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Aux. Carro',1122.66,'2023-06-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'TSI - Calculadora Eco - Cycle',5000.00,'2023-06-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.06,'2023-04-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',924.90,'2023-05-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Troco Fatura',0.95,'2023-05-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 10/12',269.00,'2023-05-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Churrasco',49.96,'2023-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Leo - Comida Show',130.00,'2023-05-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',5000.00,'2023-05-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-05-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2000.00,'2023-05-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11906.53,'2023-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',924.90,'2023-05-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Estacionamento',20.00,'2023-05-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Troco Fatura',0.01,'2023-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.29,'2023-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco',283.12,'2023-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 11/12',269.00,'2023-06-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',5000.00,'2023-06-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Férias',7991.63,'2023-04-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Férias',2663.88,'2023-04-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Abono pecuniário',5327.75,'2023-04-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Abono pecuniário',1775.92,'2023-04-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 01/02',7991.63,'2023-04-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6893.58,'2023-06-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-06-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-06-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Aluguel Carro',424.00,'2023-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Hospedagem Maragogi',350.00,'2023-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Dívida Gera',59.55,'2023-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Compras Mercadinho',55.00,'2023-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Combustível',200.00,'2023-06-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',240.00,'2023-06-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',924.90,'2023-06-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1700.00,'2023-06-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Jantar Fondue - Egon e Anne',140.00,'2023-06-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Jantar Fondue - Du e Bruna',140.05,'2023-06-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - Renovação Hospedagem',204.43,'2023-05-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -34/40',150.00,'2023-05-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -35/40',150.00,'2023-05-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',1.56,'2023-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1000.00,'2023-07-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Samara - Jantar Fondue',140.00,'2023-07-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Samara - Golpe Ingresso',250.00,'2023-07-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'FGTS - Saque Aniversário',1366.27,'2023-07-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Spotify - Eric Teixeira',34.90,'2023-07-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Acordo Faculdade - 12/12',269.00,'2023-07-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Samara - Camisa Corinthians',100.00,'2023-07-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',450.00,'2023-07-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',240.00,'2023-07-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-07-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11906.53,'2023-07-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',495.46,'2023-07-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',5000.00,'2023-07-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',3000.00,'2023-07-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',924.90,'2023-07-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',4.40,'2023-07-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas - Complemento',205.00,'2023-08-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-08-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',465.00,'2023-08-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',500.00,'2023-08-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3000.00,'2023-08-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',5000.00,'2023-08-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1350.00,'2023-08-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-08-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11906.53,'2023-08-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-08-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'IR - Restituição',356.23,'2023-08-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.17,'2023-08-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',988.00,'2023-09-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo/Samara - Jantar Beraci',72.00,'2023-09-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Transf. Egon - 2 Jantares (Ana Paula e Casa)',100.00,'2023-09-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',370.00,'2023-09-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-09-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Saque Caixa',151.00,'2023-09-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2023-09-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',800.00,'2023-09-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11906.53,'2023-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Tênis - Mercado Livre',100.00,'2023-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Dolares',3000.00,'2023-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-09-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2500.00,'2023-09-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - PSN Store - GT7',116.00,'2023-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Viagem Cajobi',224.46,'2023-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Ingressos Tardezinha',224.46,'2023-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.28,'2023-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-10-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Tardezinha',230.00,'2023-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Piano - Tardezinha',230.00,'2023-10-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'For House - Retirada',200.00,'2023-10-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Case SSD',37.00,'2023-10-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',290.00,'2023-10-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe',200.00,'2023-10-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11906.53,'2023-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Tênis - Mercado Livre',100.00,'2023-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Dolares',1000.00,'2023-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.16,'2023-10-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',1800.00,'2023-11-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',10000.00,'2023-11-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Tata e Bea - Investimento Casa',12100.00,'2023-11-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo CC - Viagem US',20000.00,'2023-11-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Western Union - Externo',9890.01,'2023-11-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',600.00,'2023-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Western Union - Externo',98.90,'2023-11-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Western Union - Externo',13.85,'2023-11-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',11906.53,'2023-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Dolares',1000.00,'2023-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',924.90,'2022-11-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',0.31,'2023-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1200.00,'2023-12-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - Convênio Mãe - Novembro',200.00,'2023-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Venda PS4',1200.00,'2023-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Henrique - Ingresso Soweto',114.00,'2023-12-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Serodio Turismo - Renovação Hospedagem',522.72,'2023-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Denis - Ingressos Soweto',240.00,'2023-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Férias',3139.39,'2023-12-14','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',10213.94,'2023-12-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 02/02',3845.40,'2023-12-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Chacará - Isaura e Célia',620.00,'2023-12-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',700.00,'2023-12-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Dolares',1000.00,'2023-12-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Celso - Ingressos Soweto',228.00,'2023-12-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Chacará - Marcela, Celso e Irda',200.00,'2023-12-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Sueli',6000.00,'2023-12-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Forhouse - Renovação Hospedagem',920.83,'2023-12-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Jogos PSN',110.00,'2023-12-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',924.90,'2023-12-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2000.00,'2023-12-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itaú',2.40,'2023-12-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Hotdog - Samara',49.00,'2021-01-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech - 05/20',150.00,'2021-01-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',232.28,'2021-01-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1341.05,'2021-01-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Spotify - Eric Teixeira',26.90,'2021-01-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pastel do Japa - Samara',14.00,'2021-01-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Espetos Bião - Ana / Emeric',52.50,'2021-01-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pizzaria da Mama - Ana / Emeric',20.00,'2021-01-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',6640.07,'2021-01-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2021-01-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',140.00,'2021-01-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Saúde',105.00,'2021-01-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Diego p/ Sueli',250.00,'2021-01-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',75.00,'2021-01-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech - 06/20',150.00,'2021-01-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',28.00,'2021-01-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',30.00,'2021-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',0.77,'2021-01-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric',50.00,'2021-02-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Extorno Fotos Maragogi',70.00,'2021-02-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole',300.00,'2021-02-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',261.57,'2021-02-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech - 07/20',150.00,'2021-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 01/10',900.00,'2021-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',7918.05,'2021-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Diferença Salário Jan',1277.98,'2021-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',0.14,'2021-02-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Saúde',277.78,'2021-03-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Spotify - Pgto Ana Paula',26.90,'2021-03-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - PLR',829.87,'2021-03-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 02/10',900.00,'2021-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',7918.05,'2021-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',0.52,'2021-03-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Du - Churrasco',78.46,'2021-04-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3.95,'2021-04-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',50.00,'2021-04-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco',277.78,'2021-04-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Academia K. - Registro BR',40.00,'2021-04-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Compra ML',204.00,'2021-04-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',3600.00,'2021-04-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole Mesa Escritório - 01/02',208.34,'2021-04-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',240.00,'2021-04-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',46.96,'2021-04-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Diferença Dissídio',1016.79,'2021-04-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8256.98,'2021-04-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 03/10',900.00,'2021-04-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech - 08/20',150.00,'2021-04-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Déposito Sueli',150.00,'2021-04-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',6.40,'2021-04-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2021-05-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Mercado',21.00,'2021-05-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',270.00,'2021-05-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',417.60,'2021-05-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',415.31,'2021-05-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Rael ML',29.00,'2021-05-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',325.99,'2021-05-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',129.00,'2021-05-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2021-05-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula - Cartão Mãe',87.00,'2021-05-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata',125.00,'2021-05-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Nestlé - 01/04',150.00,'2021-05-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Impressora',107.00,'2021-05-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 04/10',900.00,'2021-05-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8256.98,'2021-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech - 09/20',150.00,'2021-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2021-05-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Samara/Léo - Praia',228.33,'2021-05-29','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Teste Nubank',1.00,'2021-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',5.22,'2021-05-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2021-06-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',100.00,'2021-06-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',300.00,'2021-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',33.00,'2021-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',25.00,'2021-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',256.17,'2021-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',45.00,'2021-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',30.00,'2021-06-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',265.03,'2021-06-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',396.94,'2021-06-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',13.34,'2021-06-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',120.00,'2021-06-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',64.24,'2021-06-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',94.00,'2021-06-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',4.00,'2021-06-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',84.50,'2021-06-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',164.14,'2021-06-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',21.15,'2021-06-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Nestlé - 02/04',155.00,'2021-06-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -10/20',150.00,'2021-06-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -11/20',150.00,'2021-06-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Nicole',208.34,'2021-06-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8256.98,'2021-06-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 01/02',5404.00,'2021-06-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 05/10',900.00,'2021-06-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',2200.00,'2021-06-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'IR - Restituição',769.32,'2021-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Purificador - 01/10',120.00,'2021-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',7.87,'2021-06-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'FGTS - Saque Aniversário',361.41,'2021-07-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Viagem Nordeste - Samara / Léo',810.72,'2021-07-03','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Spotify - Eric Teixeira',34.90,'2021-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',266.67,'2021-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2021-07-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',141.25,'2021-07-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2021-07-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Garagem',30.00,'2021-07-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Nestlé - 03/04',100.00,'2021-07-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',279.17,'2021-07-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 06/10',900.00,'2021-07-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8256.98,'2021-07-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco Nicole',208.34,'2021-07-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Gabs - Castelo',30.00,'2021-07-28','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Purificador - 02/10',120.00,'2021-07-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',22.36,'2021-07-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Venda Ar Cond. Philco - Maycon Guerra',1500.00,'2021-08-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2021-08-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -12/20',150.00,'2021-08-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',41.90,'2021-08-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Tata - Compra ML',80.00,'2021-08-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',4362.06,'2021-08-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',110.00,'2021-08-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',537.63,'2021-08-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Nestlé - 04/04',100.00,'2021-08-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 07/10',900.00,'2021-08-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',339.65,'2021-08-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8256.98,'2021-08-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2021-08-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Purificador - 03/10',120.00,'2021-08-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Consultoria Recrutamento',110.00,'2021-08-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',24.29,'2021-08-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ana Paula - Spotify',26.90,'2021-09-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Ana Paula - Spotify',8.00,'2021-09-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',10000.00,'2021-09-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',178.81,'2021-09-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Purificador - 04/10',120.00,'2021-09-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2021-09-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',139.15,'2021-09-17','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',86.29,'2021-09-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',90.78,'2021-09-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',186.51,'2021-09-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',199.00,'2021-09-19','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 08/10',900.00,'2021-09-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8256.98,'2021-09-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -13/20',150.00,'2021-09-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -14/20',150.00,'2021-09-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',14.68,'2021-09-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Férias',5018.65,'2021-10-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Férias',2470.76,'2021-10-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Abono pecuniário',3706.16,'2021-10-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Abono pecuniário',1235.39,'2021-10-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Parto Nicolas - 09/10',900.00,'2021-10-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Carrefour - Pneus - 01/06',110.00,'2021-10-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',3675.26,'2021-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'LP Comercio de Bebidas - Extorno',3.78,'2021-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',14.53,'2021-10-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Vouchers Hannover - Caio e Nati',177.60,'2021-11-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Churrasco - Bruno Silva',120.00,'2021-11-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -15/20',150.00,'2021-11-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Kalinauskas - GymTech -16/20',150.00,'2021-11-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1699.00,'2021-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',1889.10,'2021-11-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Carrefour - Pneus - 02/06',110.00,'2021-11-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Douglas',20.00,'2021-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Zinho',30.00,'2021-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Lia',30.00,'2021-11-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Zeca',20.00,'2021-11-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Luiz Carlos',15.00,'2021-11-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Felipe',20.00,'2021-11-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Fabinho',50.00,'2021-11-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8023.05,'2021-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',116.01,'2021-10-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Acer Brasil - Estorno',1355.22,'2021-11-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Serodio Turismo - Renovação Hospedagem',376.80,'2021-11-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',40.02,'2021-11-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Carlos',20.00,'2021-12-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Dalton',5.00,'2021-12-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Lukas',25.00,'2021-12-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Jean',10.00,'2021-12-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Futebol - Lia',5.00,'2021-12-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Neto - Cinemark',71.00,'2021-12-05','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',150.00,'2021-12-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',11.75,'2021-12-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',325.67,'2021-12-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',8256.98,'2021-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 02/02',2755.98,'2021-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Du - Cinemark',120.00,'2021-12-16','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole',150.00,'2021-12-20','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana Paula  - Carrefour - Pneus - 03/06',110.00,'2021-12-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Poupança',200.00,'2022-12-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Nubank',49.67,'2021-12-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - 11/12',506.52,'2026-01-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Serodio Turismo',1100.00,'2026-01-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',14787.83,'2026-01-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Perfumes - 04/10',137.70,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Mario Galaxy - 02/10',25.00,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Carrinho Bebe - 06/12',180.39,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco - Pediatra',430.00,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook - 01/10',184.90,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Monitor - 01/10',79.90,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Lê - Presente Heloísa - 05/05',180.00,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Polo Ar - 03/10',600.00,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Samatec - 02/06',1765.00,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Nubank',15000.00,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',2000.00,'2026-01-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Mercado Livre',324.00,'2026-01-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',0.11,'2026-01-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Lourdes - 06/10',100.00,'2026-02-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Mãe - Convênio',400.00,'2026-02-04','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Léo - 12/12',506.52,'2026-02-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Eric - Spotify',122.70,'2026-02-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Férias',10100.97,'2026-02-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Férias',3366.99,'2026-02-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Abono pecuniário',6733.98,'2026-02-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 1/3 Abono pecuniário',2244.65,'2026-02-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - 13º Salário - 01/02',10100.98,'2026-02-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Yakissoba',68.00,'2026-02-13','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Churrasco Cycle',211.81,'2026-02-18','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto - Ana - Notebook - 01/12',233.07,'2026-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto - Ana - Notebook - 01/10',191.14,'2026-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Perfumes - 05/10',137.70,'2026-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Polo Ar - 04/10',623.90,'2026-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Samatec - 03/06',1766.00,'2026-02-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',12305.71,'2026-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Mario Galaxy - 03/10',25.00,'2026-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Carrinho Bebe - 07/12',180.39,'2026-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',2000.00,'2026-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Helo',310.00,'2026-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Rematricula',2754.00,'2026-02-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Monitor - 02/10',79.90,'2026-02-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook - 02/10',184.90,'2026-02-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Lourdes - 07/10',100.00,'2026-02-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',0.73,'2026-02-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Mãe - Convênio',450.00,'2026-03-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Pediatra - Heloísa',480.00,'2026-03-10','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Nicole - Uber',103.00,'2026-03-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Perfumes - 06/10',137.70,'2026-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Concerto Cobalt - 01/06',203.00,'2026-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Polo Ar - 05/10',623.90,'2026-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto - Ana - Notebook III - 02/12',233.07,'2026-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Samatec - 04/06',1766.00,'2026-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto - Ana - Notebook II - 02/10',191.14,'2026-03-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',15591.18,'2026-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Bônus',18419.42,'2026-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - PLR',734.35,'2026-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Mario Galaxy - 04/10',25.00,'2026-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Carrinho Bebe - 08/12',180.39,'2026-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - PLR',9000.00,'2026-03-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook I - 03/10',184.90,'2026-03-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Monitor - 03/10',79.90,'2026-03-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - PLR',6000.00,'2026-03-26','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Lourdes - 08/10',100.00,'2026-03-31','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',0.61,'2026-03-01','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Fabiana - 01/10',288.00,'2026-04-02','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Mãe - Convênio',650.00,'2026-04-06','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Denão - Churrasco',100.00,'2026-04-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Neguinho - Churrasco',60.00,'2026-04-11','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Diego - Churrasco',50.00,'2026-04-12','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Artboni - Reembolso',300.00,'2026-04-15','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Bradesco',528.00,'2026-04-22','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',17332.55,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Polo Ar - 06/10',623.90,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Emeric - Samatec - 05/06',1766.00,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook III - 03/12',233.07,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Concerto Cobalt - 02/06',203.00,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook II - 03/10',191.14,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Perfumes - 07/10',137.70,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',2000.00,'2026-04-24','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Mercado Livre - Gelo - 01/10',60.00,'2026-04-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Mercado Livre - 01/02',40.67,'2026-04-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Mario Galaxy - 05/10',25.00,'2026-04-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Carrinho Bebe - 09/12',180.39,'2026-04-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook I - 04/10',184.90,'2026-04-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Monitor - 04/10',79.90,'2026-04-27','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Presente Lourdes - 09/10',100.00,'2026-04-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Rendimentos Itau',0.57,'2026-04-30','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Empréstimo Fabiana - Doc Maragogi',5000.00,'2026-05-07','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Mãe - Convênio',400.00,'2026-05-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Compra Fabiana - 02/10',288.00,'2026-05-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Contas',2000.00,'2026-05-08','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Nicole - Pagto Presente Fabi',140.00,'2026-05-09','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Pediatra - Heloísa',480.00,'2026-05-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Reembolso Pediatra - Heloísa',480.00,'2026-05-21','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'RDI - Salário',17332.55,'2026-05-23','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Concerto Cobalt - 03/06',203.00,'2026-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook III - 04/12',233.07,'2026-05-25','{}','REALIZED');
  insert into entries (owner_id,description,amount,date,labels,status) values (uid,'Pagto Ana - Notebook II - 04/10',191.14,'2026-05-25','{}','REALIZED');
end $$;
