-- Atualiza as cores das categorias existentes (rodar uma vez no SQL Editor)
do $$ declare uid uuid := '69f852bc-af5a-4f11-b293-37bf2f809018'; begin
  update categories set color='#f59e0b' where owner_id=uid and lower(name)=lower('Alimentação/Mercado');
  update categories set color='#8b5cf6' where owner_id=uid and lower(name)=lower('Assinaturas');
  update categories set color='#10b981' where owner_id=uid and lower(name)=lower('Bike');
  update categories set color='#6366f1' where owner_id=uid and lower(name)=lower('Celular');
  update categories set color='#f97316' where owner_id=uid and lower(name)=lower('Combustível');
  update categories set color='#ec4899' where owner_id=uid and lower(name)=lower('Convênio Médico');
  update categories set color='#f43f5e' where owner_id=uid and lower(name)=lower('Cuidados Pessoais');
  update categories set color='#78716c' where owner_id=uid and lower(name)=lower('Despesas Carro');
  update categories set color='#84cc16' where owner_id=uid and lower(name)=lower('Despesas Casa');
  update categories set color='#0ea5e9' where owner_id=uid and lower(name)=lower('Despesas Empresa');
  update categories set color='#a3e635' where owner_id=uid and lower(name)=lower('Despesas Terreno');
  update categories set color='#6b7280' where owner_id=uid and lower(name)=lower('Diversos');
  update categories set color='#dc2626' where owner_id=uid and lower(name)=lower('Empréstimo Bancário');
  update categories set color='#b91c1c' where owner_id=uid and lower(name)=lower('Empréstimo Pessoal');
  update categories set color='#db2777' where owner_id=uid and lower(name)=lower('Enxoval');
  update categories set color='#2563eb' where owner_id=uid and lower(name)=lower('Estudo');
  update categories set color='#16a34a' where owner_id=uid and lower(name)=lower('Farmácia');
  update categories set color='#15803d' where owner_id=uid and lower(name)=lower('Futebol');
  update categories set color='#7c3aed' where owner_id=uid and lower(name)=lower('Games');
  update categories set color='#b45309' where owner_id=uid and lower(name)=lower('Instrumentos');
  update categories set color='#0d9488' where owner_id=uid and lower(name)=lower('Investimentos');
  update categories set color='#d97706' where owner_id=uid and lower(name)=lower('Lazer');
  update categories set color='#059669' where owner_id=uid and lower(name)=lower('Médico');
  update categories set color='#475569' where owner_id=uid and lower(name)=lower('Parcela carro');
  update categories set color='#92400e' where owner_id=uid and lower(name)=lower('Pets');
  update categories set color='#065f46' where owner_id=uid and lower(name)=lower('Poupança');
  update categories set color='#be185d' where owner_id=uid and lower(name)=lower('Presente');
  update categories set color='#9333ea' where owner_id=uid and lower(name)=lower('Roupas');
  update categories set color='#1d4ed8' where owner_id=uid and lower(name)=lower('TI');
  update categories set color='#991b1b' where owner_id=uid and lower(name)=lower('Tarifas/Juros');
  update categories set color='#0369a1' where owner_id=uid and lower(name)=lower('Telefone celular');
  update categories set color='#1e40af' where owner_id=uid and lower(name)=lower('Transporte Público');
  update categories set color='#7e22ce' where owner_id=uid and lower(name)=lower('Tênis');
  update categories set color='#1c1917' where owner_id=uid and lower(name)=lower('Uber/99');
  update categories set color='#0891b2' where owner_id=uid and lower(name)=lower('Viagem');
  raise notice 'Cores das categorias atualizadas';
end $$;
